# Generated by Django 3.2 on 2024-01-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('alive', models.BooleanField()),
            ],
        ),
    ]
