# Generated by Django 3.2 on 2021-05-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.TextField(),
        ),
    ]
