# Generated by Django 3.2 on 2022-01-11 18:48

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_receipt_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='parsed_file',
            field=thumbnails.fields.ImageField(default=None, null=True, upload_to='parsed_image/'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.IntegerField(choices=[(1, 'Uploaded'), (2, 'Started'), (3, 'Threshold Done'), (4, 'Parsing Done'), (5, 'Reading Done'), (6, 'Populated'), (7, 'Unable To Read')], default=1),
        ),
        migrations.AddField(
            model_name='receipt',
            name='threshhold_file',
            field=thumbnails.fields.ImageField(default=None, null=True, upload_to='threshhold_file/'),
        ),
    ]
