# Generated by Django 3.2 on 2022-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20220111_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='all_lines',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sub_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vendor',
            field=models.TextField(default='', null=True),
        ),
    ]
