# Generated by Django 3.2 on 2022-03-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20220111_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='set_fields',
            field=models.JSONField(default={}, verbose_name='SetFields'),
        ),
    ]
