# Generated by Django 3.2 on 2022-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_receipt_set_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='crop',
            field=models.JSONField(default=dict, verbose_name='crop'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='set_fields',
            field=models.JSONField(default=dict, verbose_name='SetFields'),
        ),
    ]
