# Generated by Django 3.2 on 2022-04-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_auto_20220328_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='sub_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
