# Generated by Django 3.2 on 2022-05-01 13:44

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_auto_20220402_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cropped_file',
            field=thumbnails.fields.ImageField(default=None, null=True, upload_to='cropped_image/'),
        ),
    ]
