# Generated by Django 3.2 on 2022-05-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_receipt_cropped_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Uncategorized'), (2, 'Prepay'), (3, 'Advertising'), (4, 'Tax Fee Due'), (5, 'Insurance'), (6, 'Interest'), (7, 'Maint'), (8, 'Meals'), (9, 'Office'), (10, 'Salary'), (11, 'Startup'), (12, 'Car')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.IntegerField(choices=[(1, 'Uploaded'), (2, 'Started'), (3, 'Cropped'), (4, 'Threshold Done'), (5, 'Parsing Done'), (6, 'Reading Done'), (7, 'Populated'), (8, 'Unable To Read')], default=1),
        ),
    ]
