# Generated by Django 3.2 on 2022-05-19 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_auto_20220513_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_date_datetime',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
