# Generated by Django 3.2 on 2022-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_receipt_receipt_date_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='sub_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
