# Generated by Django 3.2 on 2022-05-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0012_auto_20220521_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='vendor',
            field=models.TextField(db_index=True, default='', null=True),
        ),
    ]
