# Generated by Django 3.2 on 2022-06-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0013_alter_receipt_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cropped_file',
            field=models.ImageField(default=None, null=True, upload_to='cropped_image/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='parsed_file',
            field=models.ImageField(default=None, null=True, upload_to='parsed_image/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='threshhold_file',
            field=models.ImageField(default=None, null=True, upload_to='threshhold_file/'),
        ),
    ]
