# Generated by Django 3.2 on 2022-07-30 01:07

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0014_auto_20220624_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.ImageField(default=None, upload_to=uploader.models.content_file_name),
        ),
    ]
