# Generated by Django 3.2 on 2022-07-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0015_alter_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='thumbnail_file',
            field=models.ImageField(default=None, null=True, upload_to='thumbnail/'),
        ),
    ]
