# Generated by Django 3.2 on 2023-08-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0016_receipt_thumbnail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.IntegerField(choices=[(1, 'Uploaded'), (2, 'Started'), (3, 'Cropped'), (4, 'Threshold Done'), (5, 'Parsing Done'), (6, 'Reading Done'), (7, 'Populated'), (8, 'Unable To Read'), (9, 'Not Required')], default=1),
        ),
    ]
