RECEIPT_COUNT_DEFAULT = 20

# Set Fields
SET_FIELDS_VENDOR = "VENDOR"
SET_FIELDS_SUBTOTAL = "SUBTOTAL"
SET_FIELDS_TOTAL = "TOTAL"
SET_FIELDS_DATE = "DATE"
SET_FIELDS_DESCRIPTION = "DESCRIPTION"


# Sorting
RECEIPT_DATE_CREATED = 0
RECEIPT_DATE = 1
RECEIPT_VENDOR = 2
RECEIPT_AMOUNT_ASC = 3
RECEIPT_AMOUNT_DESC = 4
RECEIPT_DATE_CREATED_EARLY = 5
RECEIPT_DATE_EARLY = 6

# Valid Extensions
VALID_EXT = {'.tif', '.tiff', '.jpg', '.jpeg', '.png', '.bmp', '.gif'}