# Generated by Django 3.2 on 2021-12-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
