# Generated by Django 3.2 on 2022-07-30 01:07

import buckets.models
from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_activebucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='logo',
            field=thumbnails.fields.ImageField(default=None, null=True, upload_to=buckets.models.logo_file_name),
        ),
    ]
