# Generated by Django 3.2 on 2022-12-05 00:34

import buckets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0005_alter_bucket_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to=buckets.models.logo_file_name),
        ),
    ]
