# Generated by Django 3.2 on 2023-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('description', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
