# Generated by Django 3.2 on 2023-08-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authN', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['username', 'uuid'], name='reset_idx'),
        ),
    ]
